/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebadedatos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Amanda
 */
public class Pantalla extends javax.swing.JFrame {

        String DriverBD = "com.mysql.jdbc.Driver";
        String Servidor = "//localhost:3306/";
        String Base = "prueba2019";
        String Usuario = "root";
        String Clave = " ";
        String TipoCn = "jdbc:mysql:";
        
    
    
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(497, 276));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        btnListado.setText("Listado");
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel1.setText("Provincia:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setText("Nro Provincia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 210, 20));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            Class.forName(DriverBD);
            Connection cn;
            cn = (Connection)DriverManager.getConnection(TipoCn + Servidor + Base, Usuario, Clave);
            System.out.println("Conexión exitosa");
            
            String Nombre = this.txtProvincia.getText();
            this.txtProvincia.setText("");
            
            if(Nombre != ""){
                PreparedStatement ps;
                ps = cn.prepareStatement("insert into provincias(Nombre) values ('"+ Nombre +"')");
                System.out.println("\"insert into provincias(Nombre)values('\"+ Nombre +\"')\")");
                ps.execute();
                cn.close();
                System.out.println("Dato guardado");
            }
        }catch(ClassNotFoundException ex){
            System.out.println("Error en driver");
        }catch(SQLException ex){
            System.out.println("Error en sql");
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        try{
            
            Class.forName(DriverBD);
            Connection cn;
            cn = (Connection)DriverManager.getConnection(TipoCn + Servidor + Base, Usuario, Clave);
            System.out.println("Conexión exitosa");
            
            String Numero = this.txtID.getText();          
            PreparedStatement ps;
            ps = cn.prepareStatement("delete from provincias where id= "+ Numero);
            System.out.println("delete from provincias where id= "+ Numero);
            
            ps.execute();
            cn.close();
            System.out.println("Dato borrado");
            
        }catch(ClassNotFoundException ex){
            System.out.println("Error en driver");
        }catch(SQLException ex){
            System.out.println("Error en sql");
        
    }//GEN-LAST:event_btnBorrarActionPerformed
    }
    
    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        try{
            
            Class.forName(DriverBD);
            Connection cn;
            cn = (Connection)DriverManager.getConnection(TipoCn + Servidor + Base, Usuario, Clave);
            System.out.println("Conexión exitosa");
            
            String Numero = this.txtID.getText();          
            PreparedStatement ps;
            ps = cn.prepareStatement("select * from provincias order by nombre");
            System.out.println("select * from provincias order by nombre");
            
            ResultSet rs;
            rs = ps.executeQuery();
            
            while(rs.next()){
                System.out.println(rs.getObject("nombre"));
            }
            cn.close();
            
        }catch(ClassNotFoundException ex){
            System.out.println("Error en driver");
        }catch(SQLException ex){
            System.out.println("Error en sql" + ex);
        
        }        
        
    }//GEN-LAST:event_btnListadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}
