/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_7;

import javax.swing.JOptionPane;

/**
 *
 * @author Amanda
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 69, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, -1));

        jLabel2.setText("Clave:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
         //defino variables
        String usuario;
        String clave; //esto va a cambiar en un ejercicio mas adelante, se usa password 
        int largo;
        
        //obtengo el texto ingresado usando getText() 
        // y lo guardo en cada variable
        usuario = this.txtUsuario.getText();
        clave = this.txtClave.getText(); //aparece tachado porque hoy se usa otro objeto para las claves
        
        //muestro los datos ingresados a traves de un cuadro de dialogo. 
        //doy ok a la sugerencia de la lamparita: importar javax.swing.JOptionPane
        JOptionPane.showMessageDialog(this,"Hola: " + usuario + " Tu clave: " + clave);
        
        //limpio los campos de texto usando setText y con las " " para vaciar
        this.txtUsuario.setText("");
        this.txtClave.setText("");
        
        // cuento los caracteres del texto ingreado en usuario usando length()
        // y guardando en la variable largo
        largo = usuario.length();
        
        // muestro por consola el largo del texto ingresado. 
        // lo que guarde en la variable largo
        System.out.println(largo);
        
        /*paso a paso
        1- Mostrar el texto ingresado en txtUsuario en un cuadro de diÃ¡logo
        
        String usuario;
        Usuario = txtUsuario.getText();
        JOptionPane.showMessageDialog(this, usuario);
        
        2- Mostrar un saludo al texto ingresado en usuario y ver el texto por consola 
        
        String usuario;
        Usuario = txtUsuario.getText();
        JOptionPane.showMessageDialog(this,"Hola: " + usuario);
        
        3- Sumo limpiar el cuadro de texto
        
        String usuario;
        usuario = txtUsuario.getText();
        JOptionPane.showMessageDialog(this,"Hola: " + usuario);
        this.txtUsuario.setText("");
        System.out.println(usuario);
        
        Objetos con nombre:
        2 etiquetas (labels)
        2 cuadros de texto: txtUsuario y txtClave
        1 boton: btnIngresar
        */

    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
