/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase_8_9_10;

/**
 *
 * @author Amanda
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNro1 = new javax.swing.JTextField();
        txtSigno1 = new javax.swing.JTextField();
        txtNro2 = new javax.swing.JTextField();
        txtSigno2 = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnIgual = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnFlecha = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        txtSigno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSigno1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSigno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, 30));
        getContentPane().add(txtNro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 150, 30));
        getContentPane().add(txtSigno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 150, 30));
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 143, 290, 50));

        btnIgual.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnIgual.setText("=");
        getContentPane().add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 356, 50, 40));

        btn7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 224, 40, 40));

        btn8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 224, 40, 40));

        btn9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 224, 40, 40));

        btn4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 290, 40, 40));

        btn5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 40, 40));

        btn6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 40, 40));

        btn1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 356, 40, 40));

        btn2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 356, 40, 40));

        btn3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 356, 40, 40));

        btnCero.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnCero.setText("0");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 420, 40, 40));

        btnComa.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnComa.setText(",");
        btnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComaActionPerformed(evt);
            }
        });
        getContentPane().add(btnComa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 422, 40, 40));

        btnDivision.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnDivision.setText("/");
        getContentPane().add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 422, 50, 40));

        btnSuma.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 224, 50, 40));

        btnFlecha.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnFlecha.setText("<-");
        btnFlecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlechaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 224, 50, 40));

        btnResta.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnResta.setText("-");
        getContentPane().add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 50, 40));

        btnBorrar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnBorrar.setText("C");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 50, 40));

        btnMultiplicacion.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnMultiplicacion.setText("x");
        getContentPane().add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 356, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "1";
        this.txtResultado.setText(resultado);
        
        /*forma corta
        this.txtResultado.setText(this.txtResultado.getText() + "1");
        */
        /*creo una variable string (no sirve para cuentas matemáticas)
        Obtengo el contenido de txtResultado a través de getText().
        A la variable resultado le agrego un "1" y lo vuelvo a 
        guardar para que lo guarde al final de la línea.
        Devuelvo el valor con el "1" a través de setText().
        Lo veo en txtResultado al hacer click en el botón 1.
        */
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComaActionPerformed
   
        String resultado;
        resultado = this.txtResultado.getText();
        if (resultado.indexOf(".") == -1) {
            resultado = resultado + ".";
            this.txtResultado.setText(resultado);
        }
       
        /*IndexOf me devuelve el primer lugar donde encuentro "el punto".
        Si no tiene nada queda como "-1" */
    }//GEN-LAST:event_btnComaActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "2";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "3";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "4";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "5";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "6";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "7";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "8";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "9";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        
        String resultado;
        resultado = this.txtResultado.getText();
        resultado = resultado + "0";
        this.txtResultado.setText(resultado);
        
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        this.txtResultado.setText("0.00");
        this.txtNro1.setText(" ");
        this.txtSigno1.setText(" ");
        this.txtNro2.setText(" ");
        this.txtSigno2.setText(" ");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnFlechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlechaActionPerformed
        
        int largo;
        String resultado;
        
        largo = this.txtResultado.getText().length();
        resultado = this.txtResultado.getText();
        
        if (largo > 0) {
            resultado = resultado.substring(0, largo -1);
            this.txtResultado.setText(resultado);
        }
        /* creo una variable de tipo entero.
        obtengo el largo (length) del contenido del txtResultado y lo guardo en la variable largo.
        obtengo el contenido de txtResultado y lo guardo en la variable resultado.
        substring me devuelve la porción de caracteres que quiero. De 0 al largo - 1. devuelve todo
        menos el último caracter.
        Muestro o le asigno el valor de la variable resultado al txtResultado
        Sumo una condición if para que no produzca error cuando se presione flecha muchas veces.
        Se va a ejecutar si se cumple la condición. largo es mayor a cero.
        Devuelvo el resultado al contenido de txtResultado menos un caracter.
        Y devuelvo el contenido a txtResultado
        */
    }//GEN-LAST:event_btnFlechaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        
        if ("+".equals(this.txtSigno1.getText())){
            this.txtNro2.setText(this.txtResultado.getText());
            this.txtSigno2.setText("+");
            this.txtResultado.setText("Subtotal: ");
        }else{
            this.txtNro1.setText(this.txtResultado.getText());
            this.txtSigno1.setText("+");
            this.txtResultado.setText(" ");
        }
        
        /*
        Usando las formas cortas a través de getText de txtResultado y lo llevo (lo muestro)
        en el txtNro1 a través de setText
        Muestro el signo "+" en el txtSigno1 a través de setText
        Limpio el txtResultado(" ") para ingresar otro número
        Si el contenido del txtSigno1 es igual a "+"
        En las comparaciones uso doble "=" 
        si el signo "+" está dentro de txtSignos
        */
        
    }//GEN-LAST:event_btnSumaActionPerformed

    private void txtSigno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSigno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSigno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnFlecha;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JTextField txtNro1;
    private javax.swing.JTextField txtNro2;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtSigno1;
    private javax.swing.JTextField txtSigno2;
    // End of variables declaration//GEN-END:variables
}
