/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication30;

import javax.swing.JButton;

/**
 *
 * @author balbi
 */
public class Pantalla extends javax.swing.JFrame {
String preguntas[][] = new String[28][4];
  Metodos MM = new Metodos();

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        preguntas[0][0] = "Cuantas patas tiene un leon?";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblpregunta = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnTiempo = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnA3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnA4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnA5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnA6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnA7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnA8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnA9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("A");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, 50, 37, 50);

        lblpregunta.setForeground(new java.awt.Color(255, 255, 0));
        lblpregunta.setText("-");
        jPanel1.add(lblpregunta);
        lblpregunta.setBounds(170, 310, 700, 60);

        btnIniciar.setText("Iniciar Juego");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar);
        btnIniciar.setBounds(1030, 530, 200, 23);

        btnA.setBackground(new java.awt.Color(51, 255, 204));
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnA.setBorder(null);
        btnA.setBorderPainted(false);
        btnA.setContentAreaFilled(false);
        btnA.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA);
        btnA.setBounds(560, 50, 60, 60);

        btnTiempo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnTiempo.setText("Tiempo");
        jPanel1.add(btnTiempo);
        btnTiempo.setBounds(1030, 390, 90, 130);

        btnFin.setText("Finalizar Juego");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        jPanel1.add(btnFin);
        btnFin.setBounds(1030, 250, 200, 23);

        jLabel5.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("C");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(720, 80, 40, 60);

        btnA3.setBackground(new java.awt.Color(51, 255, 204));
        btnA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnA3.setBorder(null);
        btnA3.setBorderPainted(false);
        btnA3.setContentAreaFilled(false);
        btnA3.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA3.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA3.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA3);
        btnA3.setBounds(710, 80, 60, 60);

        jLabel6.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("B");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(650, 70, 40, 40);

        btnA4.setBackground(new java.awt.Color(51, 255, 204));
        btnA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnA4.setBorder(null);
        btnA4.setBorderPainted(false);
        btnA4.setContentAreaFilled(false);
        btnA4.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA4.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA4.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA4);
        btnA4.setBounds(640, 60, 60, 60);

        jLabel7.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setText("D");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(780, 130, 40, 40);

        btnA5.setBackground(new java.awt.Color(51, 255, 204));
        btnA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/amarillo.png"))); // NOI18N
        btnA5.setBorder(null);
        btnA5.setBorderPainted(false);
        btnA5.setContentAreaFilled(false);
        btnA5.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA5.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA5.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA5);
        btnA5.setBounds(770, 120, 60, 60);

        jLabel8.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setText("E");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(830, 170, 37, 60);

        btnA6.setBackground(new java.awt.Color(51, 255, 204));
        btnA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnA6.setBorder(null);
        btnA6.setBorderPainted(false);
        btnA6.setContentAreaFilled(false);
        btnA6.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA6.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA6.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA6);
        btnA6.setBounds(820, 170, 60, 60);

        jLabel9.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 102));
        jLabel9.setText("F");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(877, 250, 40, 40);

        btnA7.setBackground(new java.awt.Color(51, 255, 204));
        btnA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnA7.setBorder(null);
        btnA7.setBorderPainted(false);
        btnA7.setContentAreaFilled(false);
        btnA7.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA7.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA7.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA7);
        btnA7.setBounds(860, 240, 60, 60);

        jLabel10.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 102));
        jLabel10.setText("G");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(900, 310, 50, 50);

        btnA8.setBackground(new java.awt.Color(51, 255, 204));
        btnA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/rojo.png"))); // NOI18N
        btnA8.setBorder(null);
        btnA8.setBorderPainted(false);
        btnA8.setContentAreaFilled(false);
        btnA8.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA8.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA8.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA8);
        btnA8.setBounds(890, 310, 60, 60);

        jLabel11.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 102));
        jLabel11.setText("H");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(910, 400, 40, 40);

        btnA9.setBackground(new java.awt.Color(51, 255, 204));
        btnA9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/verde.png"))); // NOI18N
        btnA9.setBorder(null);
        btnA9.setBorderPainted(false);
        btnA9.setContentAreaFilled(false);
        btnA9.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA9.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA9.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA9);
        btnA9.setBounds(900, 390, 60, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/ecualizador.gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 630, 310, 76);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASAPALABRA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 20, 430, 120);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("PASAPALABRA");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 40, 430, 120);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/fondoazul.jpg"))); // NOI18N
        jPanel1.add(Fondo);
        Fondo.setBounds(-10, 20, 1670, 720);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
      
   //     MM.btncolor(cuales(1), "amarillo");
        MM.btncolor(btnA, "rojo");
        lblpregunta.setText(preguntas[0][0]);
        MM.cartel(lblpregunta);
        MM.tiempo(btnTiempo);
        
  
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
    
       lblpregunta.setText("");
       MM.setSegundos(60); //desde pantalla.java indico el valor a variable "segundos" en Métodos
    }//GEN-LAST:event_btnFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

      public JButton cuales(int numero){
        
        return btnA;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnA5;
    private javax.swing.JButton btnA6;
    private javax.swing.JButton btnA7;
    private javax.swing.JButton btnA8;
    private javax.swing.JButton btnA9;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpregunta;
    // End of variables declaration//GEN-END:variables
}
