package pasapalabra;

public class Rosco extends javax.swing.JFrame {

Metodos MM = new Metodos();
        
    public Rosco() {
        initComponents();
        MM.BTNColor(BTNA, "azul.PNG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BTNA = new javax.swing.JButton();
        BTNIniciar = new javax.swing.JButton();
        BTNA1 = new javax.swing.JButton();
        BTNA2 = new javax.swing.JButton();
        BTNA3 = new javax.swing.JButton();
        BTNA4 = new javax.swing.JButton();
        BTNA5 = new javax.swing.JButton();
        BTNA6 = new javax.swing.JButton();
        BTNA7 = new javax.swing.JButton();
        BTNA8 = new javax.swing.JButton();
        BTNA9 = new javax.swing.JButton();
        BTNA10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("D");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("F");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("C");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("B");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        BTNA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA.setBorder(null);
        jPanel1.add(BTNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 60, 60));

        BTNIniciar.setText("Iniciar juego");
        BTNIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(BTNIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 11, -1, -1));

        BTNA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA1.setBorder(null);
        jPanel1.add(BTNA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 60, 60));

        BTNA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA2.setBorder(null);
        BTNA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNA2ActionPerformed(evt);
            }
        });
        jPanel1.add(BTNA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 60, 60));

        BTNA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA3.setBorder(null);
        jPanel1.add(BTNA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 60, 60));

        BTNA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA4.setBorder(null);
        jPanel1.add(BTNA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 60, 60));

        BTNA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA5.setBorder(null);
        jPanel1.add(BTNA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, 60, 60));

        BTNA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA6.setBorder(null);
        jPanel1.add(BTNA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 60, 60));

        BTNA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA7.setBorder(null);
        jPanel1.add(BTNA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 60, 60));

        BTNA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA8.setBorder(null);
        jPanel1.add(BTNA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 60, 60));

        BTNA9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA9.setBorder(null);
        jPanel1.add(BTNA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 60, 60));

        BTNA10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasapalabra/azul.PNG"))); // NOI18N
        BTNA10.setBorder(null);
        jPanel1.add(BTNA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIniciarActionPerformed
        MM.BTNColor(BTNA, "naranja.PNG");
    }//GEN-LAST:event_BTNIniciarActionPerformed

    private void BTNA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNA2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rosco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNA;
    private javax.swing.JButton BTNA1;
    private javax.swing.JButton BTNA10;
    private javax.swing.JButton BTNA2;
    private javax.swing.JButton BTNA3;
    private javax.swing.JButton BTNA4;
    private javax.swing.JButton BTNA5;
    private javax.swing.JButton BTNA6;
    private javax.swing.JButton BTNA7;
    private javax.swing.JButton BTNA8;
    private javax.swing.JButton BTNA9;
    private javax.swing.JButton BTNIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
